[[service]]
name = "tictactoe-frontend"
  [service.build]
  builder = "NIXPACKS"
  buildCommand = "pnpm install --frozen-lockfile && pnpm run build:client"
  [service.deploy]
  startCommand = "pnpm start:client"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
  [service.variables]
  NODE_ENV = "production"

[[service]]
name = "tictactoe-socket"
  [service.build]
  builder = "NIXPACKS"
  buildCommand = "pnpm install --frozen-lockfile && pnpm run build:server"
  [service.deploy]
  startCommand = "pnpm start:server"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
  [service.variables]
  NODE_ENV = "production"