services:
  - type: web
    name: tictactoe-frontend
    env: node
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://your-socket-server-url.com

  - type: web
    name: tictactoe-socket
    env: node
    buildCommand: pnpm install && pnpm run server:build
    startCommand: pnpm run server:start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
